# Week 3 - Peer-Graded Assignment

`Author: Andersen Lin`<br><br>
`Date: May 23, 2020`<br><br>
`GitHub:` __[github.com/Andersen1997](https://github.com/Andersen1997)__ <br><br>
`LinkedIn:` __[linkedin.com/in/andersen-lin/](https://www.linkedin.com/in/andersen-lin/)__

<div style="font-size:16px">
<h3><a id = "0"><font color = black>Table of Contents</font></a></h3>
<ol>
    <li><a href = "#1">Part1 (10 marks)</a></li>
    <li><a href = "#2">Part2 (2 marks)</a></li>
    <li><a href = "#3">Part3 (3 marks)</a></li>
</ol>
</div>
<div class="alert alert-block alert-success" style="font-size:16px">
<b>Note:</b> This notebook is mainly used for a weekly project of Applied Data Science Capstone by IBM on Coursera. It is shared on my GitHub repository for peer-to-peer review and grading. 
</div>

<h2><a id = "1">Part1 (10 marks)</a>&emsp;<a href = "#0" style = "text-decoration:none;">↑</a></h2>

In [1]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup

In [2]:
postal_member = []

res = requests.get("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M").text
soup = BeautifulSoup(res, "html.parser")

# identify table we want to scrape
postal_table = soup.find('table', {"class" : "wikitable sortable"})

# loop through table, grab each of the 3 columns shown
for row in postal_table.find_all('tr'):
    cols = row.find_all('td')
    if len(cols) == 3:
        postal_member.append((cols[0].text.strip(), cols[1].text.strip(), cols[2].text.strip()))

# assign to a new array
postal_array = np.asarray(postal_member)
len(postal_array)

# convert to a dataframe
df = pd.DataFrame(postal_array)
df.columns = ['PostalCode', 'Borough', 'Neighborhood']
df

PostalCode           Borough  \
0          M1A      Not assigned   
1          M2A      Not assigned   
2          M3A        North York   
3          M4A        North York   
4          M5A  Downtown Toronto   
..         ...               ...   
175        M5Z      Not assigned   
176        M6Z      Not assigned   
177        M7Z      Not assigned   
178        M8Z         Etobicoke   
179        M9Z      Not assigned   

                                          Neighborhood  
0                                                       
1                                                       
2                                            Parkwoods  
3                                     Victoria Village  
4                            Regent Park, Harbourfront  
..                                                 ...  
175                                                     
176                                                     
177                                                     
178  Mimico NW, The Queensway West, South of Bloor,...  
179                                                     

[180 rows x 3 columns]

In [3]:
# ensure only not assigned cells will be dropped
df['Borough'].describe()

count              180
unique              11
top       Not assigned
freq                77
Name: Borough, dtype: object

In [4]:
# ignore cells whose borough is not assigned
df_assigned = df[df['Borough'] != 'Not assigned'].reset_index(drop = True)
df_assigned

PostalCode           Borough  \
0          M3A        North York   
1          M4A        North York   
2          M5A  Downtown Toronto   
3          M6A        North York   
4          M7A  Downtown Toronto   
..         ...               ...   
98         M8X         Etobicoke   
99         M4Y  Downtown Toronto   
100        M7Y      East Toronto   
101        M8Y         Etobicoke   
102        M8Z         Etobicoke   

                                          Neighborhood  
0                                            Parkwoods  
1                                     Victoria Village  
2                            Regent Park, Harbourfront  
3                     Lawrence Manor, Lawrence Heights  
4          Queen's Park, Ontario Provincial Government  
..                                                 ...  
98       The Kingsway, Montgomery Road, Old Mill North  
99                                Church and Wellesley  
100  Business reply mail Processing Centre, South C...  
101  Old Mill South, King's Mill Park, Sunnylea, Hu...  
102  Mimico NW, The Queensway West, South of Bloor,...  

[103 rows x 3 columns]

In [5]:
df_assigned['PostalCode'].describe()

count     103
unique    103
top       M5W
freq        1
Name: PostalCode, dtype: object

**Multiple neighborhoods were already combined into one rows on Wiki**

In [6]:
df_assigned[df_assigned.Neighborhood == 'Not assigned']

Empty DataFrame
Columns: [PostalCode, Borough, Neighborhood]
Index: []

**There is no neighborhood that is 'Not assigned'**

In [7]:
df_assigned.shape

(103, 3)

***

<h2><a id = "2">Part2 (2 marks)</a>&emsp;<a href = "#0" style = "text-decoration:none;">↑</a></h2>

In [8]:
import geocoder

In [9]:
# test if we could get coordinates by the package
g = geocoder.google('Mountain View, CA')
g.latlng

**Could not get information from Geocoder. Import from the csv file instead**

In [10]:
df_coord = pd.read_csv('Geospatial_Coordinates.csv')
df_coord

Postal Code   Latitude  Longitude
0           M1B  43.806686 -79.194353
1           M1C  43.784535 -79.160497
2           M1E  43.763573 -79.188711
3           M1G  43.770992 -79.216917
4           M1H  43.773136 -79.239476
..          ...        ...        ...
98          M9N  43.706876 -79.518188
99          M9P  43.696319 -79.532242
100         M9R  43.688905 -79.554724
101         M9V  43.739416 -79.588437
102         M9W  43.706748 -79.594054

[103 rows x 3 columns]

**Ensure the number of unique postal codes in `df_coord` is the same as `df_assigned`**

In [11]:
df_coord['Postal Code'].describe()

count     103
unique    103
top       M5W
freq        1
Name: Postal Code, dtype: object

In [12]:
# merge the two dataframes and drop repeated Postal Code column
df_poscoord = pd.merge(left = df_assigned, right = df_coord, how = 'left', left_on = 'PostalCode', right_on = 'Postal Code')
df_poscoord = df_poscoord.drop(columns = ['Postal Code'])
df_poscoord

PostalCode           Borough  \
0          M3A        North York   
1          M4A        North York   
2          M5A  Downtown Toronto   
3          M6A        North York   
4          M7A  Downtown Toronto   
..         ...               ...   
98         M8X         Etobicoke   
99         M4Y  Downtown Toronto   
100        M7Y      East Toronto   
101        M8Y         Etobicoke   
102        M8Z         Etobicoke   

                                          Neighborhood   Latitude  Longitude  
0                                            Parkwoods  43.753259 -79.329656  
1                                     Victoria Village  43.725882 -79.315572  
2                            Regent Park, Harbourfront  43.654260 -79.360636  
3                     Lawrence Manor, Lawrence Heights  43.718518 -79.464763  
4          Queen's Park, Ontario Provincial Government  43.662301 -79.389494  
..                                                 ...        ...        ...  
98       The Kingsway, Montgomery Road, Old Mill North  43.653654 -79.506944  
99                                Church and Wellesley  43.665860 -79.383160  
100  Business reply mail Processing Centre, South C...  43.662744 -79.321558  
101  Old Mill South, King's Mill Park, Sunnylea, Hu...  43.636258 -79.498509  
102  Mimico NW, The Queensway West, South of Bloor,...  43.628841 -79.520999  

[103 rows x 5 columns]

In [13]:
df_poscoord.shape

(103, 5)

***

<h2><a id = "3">Part3 (3 marks)</a>&emsp;<a href = "#0" style = "text-decoration:none;">↑</a></h2>

In [14]:
df_poscoord['Borough'].unique()

array(['North York', 'Downtown Toronto', 'Etobicoke', 'Scarborough',
       'East York', 'York', 'East Toronto', 'West Toronto',
       'Central Toronto', 'Mississauga'], dtype=object)

In [15]:
# filter the dataframe to get neighbordhoods in Toronto
df_poscoord = df_poscoord[df_poscoord['Borough'].str.contains("Toronto")].reset_index(drop = True)
df_poscoord.shape

(39, 5)

**There are 39 neighborhoods in Toronto**

In [16]:
import json
from geopy.geocoders import Nominatim
from pandas.io.json import json_normalize
import matplotlib.cm as cm
import matplotlib.colors as colors
from sklearn.cluster import KMeans
import folium

**Use geopy library to get the coordinate of Toronto**

In [17]:
address = 'Toronto, Ontario'

geolocator = Nominatim(user_agent = "ny_explorer")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of Toronto are {}, {}.'.format(latitude, longitude))

The geograpical coordinate of Toronto are 43.6534817, -79.3839347.


In [18]:
# create map of Toronto using latitude and longitude values
map_toronto = folium.Map(location = [latitude, longitude], zoom_start = 12)

# add markers to map
for lat, lng, borough, neighborhood in zip(df_poscoord['Latitude'], df_poscoord['Longitude'], df_poscoord['Borough'], df_poscoord['Neighborhood']):
    label = '{}, {}'.format(neighborhood, borough)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius = 5,
        popup = label,
        color = 'blue',
        fill = True,
        fill_color = '#3186cc',
        fill_opacity = 0.7,
        parse_html = False).add_to(map_toronto)  
    
map_toronto

In [57]:
# as folium maps will not display on GitHub, save it as an .html file then display
map_toronto.save('before_clustering.html')

In [66]:
import webbrowser
webbrowser.open("before_clustering.html")

True

In [64]:
from IPython.display import Image
# Image(filename='Taichi.png') 

**Use the Foursquare API to explore the neighborhoods and segment them**

In [19]:
CLIENT_ID = 'T1NVRT5GLC44RVGSBIJZZQOX3T0RPLG5HUBLAVPGMGVIO2YJ' # your Foursquare ID
CLIENT_SECRET = '3OPOUJLAXJQVHSS5MDSVQFO2IUZIZE4ZWNV54M1ISIGZSB5F' # your Foursquare Secret
VERSION = '20180605' # Foursquare API version

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: T1NVRT5GLC44RVGSBIJZZQOX3T0RPLG5HUBLAVPGMGVIO2YJ
CLIENT_SECRET:3OPOUJLAXJQVHSS5MDSVQFO2IUZIZE4ZWNV54M1ISIGZSB5F


**Create a function to explore all neighborhoods in Toronto**

In [20]:
def getNearbyVenues(names, latitudes, longitudes, radius = 500):
    
    venues_list = []
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

In [21]:
LIMIT = 100 # limit of number of venues returned by Foursquare API

toronto_venues = getNearbyVenues(names = df_poscoord['Neighborhood'],
                                   latitudes = df_poscoord['Latitude'],
                                   longitudes = df_poscoord['Longitude']
                                  )

Regent Park, Harbourfront
Queen's Park, Ontario Provincial Government
Garden District, Ryerson
St. James Town
The Beaches
Berczy Park
Central Bay Street
Christie
Richmond, Adelaide, King
Dufferin, Dovercourt Village
Harbourfront East, Union Station, Toronto Islands
Little Portugal, Trinity
The Danforth West, Riverdale
Toronto Dominion Centre, Design Exchange
Brockton, Parkdale Village, Exhibition Place
India Bazaar, The Beaches West
Commerce Court, Victoria Hotel
Studio District
Lawrence Park
Roselawn
Davisville North
Forest Hill North & West, Forest Hill Road Park
High Park, The Junction South
North Toronto West,  Lawrence Park
The Annex, North Midtown, Yorkville
Parkdale, Roncesvalles
Davisville
University of Toronto, Harbord
Runnymede, Swansea
Moore Park, Summerhill East
Kensington Market, Chinatown, Grange Park
Summerhill West, Rathnelly, South Hill, Forest Hill SE, Deer Park
CN Tower, King and Spadina, Railway Lands, Harbourfront West, Bathurst Quay, South Niagara, Island airport


In [22]:
# check the size of the resulting dataframe
print(toronto_venues.shape)
toronto_venues.head()

(1605, 7)


Neighborhood  Neighborhood Latitude  Neighborhood Longitude  \
0  Regent Park, Harbourfront               43.65426              -79.360636   
1  Regent Park, Harbourfront               43.65426              -79.360636   
2  Regent Park, Harbourfront               43.65426              -79.360636   
3  Regent Park, Harbourfront               43.65426              -79.360636   
4  Regent Park, Harbourfront               43.65426              -79.360636   

                    Venue  Venue Latitude  Venue Longitude  \
0        Roselle Desserts       43.653447       -79.362017   
1           Tandem Coffee       43.653559       -79.361809   
2      Morning Glory Cafe       43.653947       -79.361149   
3  Cooper Koo Family YMCA       43.653249       -79.358008   
4     Body Blitz Spa East       43.654735       -79.359874   

        Venue Category  
0               Bakery  
1          Coffee Shop  
2       Breakfast Spot  
3  Distribution Center  
4                  Spa

In [23]:
# check the number of venues returned for each neighborhood
toronto_venues.groupby('Neighborhood').count()

Neighborhood Latitude  \
Neighborhood                                                                
Berczy Park                                                            56   
Brockton, Parkdale Village, Exhibition Place                           23   
Business reply mail Processing Centre, South Ce...                     17   
CN Tower, King and Spadina, Railway Lands, Harb...                     15   
Central Bay Street                                                     62   
Christie                                                               17   
Church and Wellesley                                                   76   
Commerce Court, Victoria Hotel                                        100   
Davisville                                                             34   
Davisville North                                                        7   
Dufferin, Dovercourt Village                                           14   
First Canadian Place, Underground city                                100   
Forest Hill North & West, Forest Hill Road Park                         5   
Garden District, Ryerson                                              100   
Harbourfront East, Union Station, Toronto Islands                     100   
High Park, The Junction South                                          23   
India Bazaar, The Beaches West                                         20   
Kensington Market, Chinatown, Grange Park                              58   
Lawrence Park                                                           4   
Little Portugal, Trinity                                               43   
Moore Park, Summerhill East                                             3   
North Toronto West,  Lawrence Park                                     23   
Parkdale, Roncesvalles                                                 14   
Queen's Park, Ontario Provincial Government                            34   
Regent Park, Harbourfront                                              48   
Richmond, Adelaide, King                                               92   
Rosedale                                                                4   
Roselawn                                                                2   
Runnymede, Swansea                                                     37   
St. James Town                                                         77   
St. James Town, Cabbagetown                                            46   
Stn A PO Boxes                                                         92   
Studio District                                                        40   
Summerhill West, Rathnelly, South Hill, Forest ...                     16   
The Annex, North Midtown, Yorkville                                    23   
The Beaches                                                             4   
The Danforth West, Riverdale                                           42   
Toronto Dominion Centre, Design Exchange                              100   
University of Toronto, Harbord                                         34   

                                                    Neighborhood Longitude  \
Neighborhood                                                                 
Berczy Park                                                             56   
Brockton, Parkdale Village, Exhibition Place                            23   
Business reply mail Processing Centre, South Ce...                      17   
CN Tower, King and Spadina, Railway Lands, Harb...                      15   
Central Bay Street                                                      62   
Christie                                                                17   
Church and Wellesley                                                    76   
Commerce Court, Victoria Hotel                                         100   
Davisville                                                              34   
Davisville North                    

**Find out the number of unique venue categories**

In [24]:
print('There are {} uniques categories.'.format(len(toronto_venues['Venue Category'].unique())))

There are 235 uniques categories.


**Analyze each neighborhood**

In [25]:
# one hot encoding
toronto_onehot = pd.get_dummies(toronto_venues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
toronto_onehot['Neighborhood'] = toronto_venues['Neighborhood'] 

# move neighborhood column to the first column
fixed_columns = [toronto_onehot.columns[-1]] + list(toronto_onehot.columns[:-1])
toronto_onehot = toronto_onehot[fixed_columns]

print(toronto_onehot.shape)
toronto_onehot.head()

(1605, 235)


Yoga Studio  Afghan Restaurant  Airport  Airport Food Court  Airport Gate  \
0            0                  0        0                   0             0   
1            0                  0        0                   0             0   
2            0                  0        0                   0             0   
3            0                  0        0                   0             0   
4            0                  0        0                   0             0   

   Airport Lounge  Airport Service  Airport Terminal  American Restaurant  \
0               0                0                 0                    0   
1               0                0                 0                    0   
2               0                0                 0                    0   
3               0                0                 0                    0   
4               0                0                 0                    0   

   Antique Shop  ...  Theme Restaurant  Toy / Game Store  Trail  \
0             0  ...                 0                 0      0   
1             0  ...                 0                 0      0   
2             0  ...                 0                 0      0   
3             0  ...                 0                 0      0   
4             0  ...                 0                 0      0   

   Train Station  Vegetarian / Vegan Restaurant  Video Game Store  \
0              0                              0                 0   
1              0                              0                 0   
2              0                              0                 0   
3              0                              0                 0   
4              0                              0                 0   

   Vietnamese Restaurant  Wine Bar  Wings Joint  Women's Store  
0                      0         0            0              0  
1                      0         0            0              0  
2                      0         0            0              0  
3                      0         0            0              0  
4                      0         0            0              0  

[5 rows x 235 columns]

**There are 1605 venues with 235 different categories**

In [26]:
# group rows by neighborhood and take mean of the frequency of occurrence of each category
toronto_grouped = toronto_onehot.groupby('Neighborhood').mean().reset_index()

# confirm that there should be 39 rows
print(toronto_grouped.shape)
toronto_grouped

(39, 235)


Neighborhood  Yoga Studio  \
0                                         Berczy Park     0.000000   
1        Brockton, Parkdale Village, Exhibition Place     0.000000   
2   Business reply mail Processing Centre, South C...     0.058824   
3   CN Tower, King and Spadina, Railway Lands, Har...     0.000000   
4                                  Central Bay Street     0.016129   
5                                            Christie     0.000000   
6                                Church and Wellesley     0.026316   
7                      Commerce Court, Victoria Hotel     0.000000   
8                                          Davisville     0.000000   
9                                    Davisville North     0.000000   
10                       Dufferin, Dovercourt Village     0.000000   
11             First Canadian Place, Underground city     0.000000   
12    Forest Hill North & West, Forest Hill Road Park     0.000000   
13                           Garden District, Ryerson     0.000000   
14  Harbourfront East, Union Station, Toronto Islands     0.000000   
15                      High Park, The Junction South     0.000000   
16                     India Bazaar, The Beaches West     0.000000   
17          Kensington Market, Chinatown, Grange Park     0.000000   
18                                      Lawrence Park     0.000000   
19                           Little Portugal, Trinity     0.023256   
20                        Moore Park, Summerhill East     0.000000   
21                 North Toronto West,  Lawrence Park     0.043478   
22                             Parkdale, Roncesvalles     0.000000   
23        Queen's Park, Ontario Provincial Government     0.029412   
24                          Regent Park, Harbourfront     0.020833   
25                           Richmond, Adelaide, King     0.000000   
26                                           Rosedale     0.000000   
27                                           Roselawn     0.000000   
28                                 Runnymede, Swansea     0.000000   
29                                     St. James Town     0.000000   
30                        St. James Town, Cabbagetown     0.000000   
31                                     Stn A PO Boxes     0.010870   
32                                    Studio District     0.025000   
33  Summerhill West, Rathnelly, South Hill, Forest...     0.000000   
34                The Annex, North Midtown, Yorkville     0.000000   
35                                        The Beaches     0.000000   
36                       The Danforth West, Riverdale     0.023810   
37           Toronto Dominion Centre, Design Exchange     0.000000   
38                     University of Toronto, Harbord     0.029412   

    Afghan Restaurant   Airport  Airport Food Court  Airport Gate  \
0            0.000000  0.000000            0.000000      0.000000   
1            0.000000  0.000000            0.000000      0.000000   
2            0.000000  0.000000            0.000000      0.000000   
3            0.000000  0.066667            0.066667      0.066667   
4            0.000000  0.000000            0.000000      0.000000   
5            0.000000  0.000000            0.000000      0.000000   
6            0.013158  0.000000            0.000000      0.000000   
7            0.000000  0.000000            0.000000      0.000000   
8            0.000000  0.000000            0.000000      0.000000   
9            0.000000  0.000000            0.000000      0.000000   
10           0.000000  0.000000            0.000000      0.000000   
11           0.000000  0.000000            0.000000      0.000000   
12           0.000000  0.000000            0.000000      0.000000   
13           0.000000  0.000000            0.000000      0.000000   
14           0.000000  0.000000            0.000000      0.000000   
15           0.000000  0.000000            0.000000      0.000000   
16           0.000000  0.000000            0.000000      0.000000  

In [27]:
# sort the venues in descending order
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

**Create a dataframe with the top 10 venues for each neighborhood**

In [28]:
num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Neighborhood']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
neighborhoods_venues_sorted = pd.DataFrame(columns = columns)
neighborhoods_venues_sorted['Neighborhood'] = toronto_grouped['Neighborhood']

for ind in np.arange(toronto_grouped.shape[0]):
    neighborhoods_venues_sorted.iloc[ind, 1:] = return_most_common_venues(toronto_grouped.iloc[ind, :], num_top_venues)

neighborhoods_venues_sorted.head()

Neighborhood 1st Most Common Venue  \
0                                        Berczy Park           Coffee Shop   
1       Brockton, Parkdale Village, Exhibition Place                  Café   
2  Business reply mail Processing Centre, South C...           Yoga Studio   
3  CN Tower, King and Spadina, Railway Lands, Har...       Airport Service   
4                                 Central Bay Street           Coffee Shop   

  2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
0          Cocktail Bar    Seafood Restaurant              Beer Bar   
1           Coffee Shop        Breakfast Spot             Nightclub   
2         Auto Workshop         Garden Center                Garden   
3      Airport Terminal        Airport Lounge         Boat or Ferry   
4    Italian Restaurant                  Café        Sandwich Place   

  5th Most Common Venue 6th Most Common Venue 7th Most Common Venue  \
0                Bakery           Cheese Shop                  Café   
1                Bakery     Convenience Store                   Bar   
2  Gym / Fitness Center  Fast Food Restaurant        Farmers Market   
3           Coffee Shop       Harbor / Marina      Sculpture Garden   
4                   Bar   Japanese Restaurant        Ice Cream Shop   

  8th Most Common Venue 9th Most Common Venue 10th Most Common Venue  
0            Restaurant                   Pub          Shopping Mall  
1          Intersection    Italian Restaurant             Restaurant  
2    Light Rail Station            Comic Shop            Pizza Place  
3                   Bar          Airport Gate     Airport Food Court  
4       Thai Restaurant          Burger Joint            Salad Place

**Cluster neighborhoods**

In [29]:
# set number of clusters
kclusters = 10

toronto_grouped_clustering = toronto_grouped.drop('Neighborhood', 1)

# run k-means clustering
kmeans = KMeans(n_clusters = kclusters, random_state = 0).fit(toronto_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10] 

array([7, 0, 0, 9, 7, 0, 7, 7, 0, 8], dtype=int32)

In [30]:
# add clustering labels
neighborhoods_venues_cluster = neighborhoods_venues_sorted.copy()
neighborhoods_venues_cluster.head()

Neighborhood 1st Most Common Venue  \
0                                        Berczy Park           Coffee Shop   
1       Brockton, Parkdale Village, Exhibition Place                  Café   
2  Business reply mail Processing Centre, South C...           Yoga Studio   
3  CN Tower, King and Spadina, Railway Lands, Har...       Airport Service   
4                                 Central Bay Street           Coffee Shop   

  2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
0          Cocktail Bar    Seafood Restaurant              Beer Bar   
1           Coffee Shop        Breakfast Spot             Nightclub   
2         Auto Workshop         Garden Center                Garden   
3      Airport Terminal        Airport Lounge         Boat or Ferry   
4    Italian Restaurant                  Café        Sandwich Place   

  5th Most Common Venue 6th Most Common Venue 7th Most Common Venue  \
0                Bakery           Cheese Shop                  Café   
1                Bakery     Convenience Store                   Bar   
2  Gym / Fitness Center  Fast Food Restaurant        Farmers Market   
3           Coffee Shop       Harbor / Marina      Sculpture Garden   
4                   Bar   Japanese Restaurant        Ice Cream Shop   

  8th Most Common Venue 9th Most Common Venue 10th Most Common Venue  
0            Restaurant                   Pub          Shopping Mall  
1          Intersection    Italian Restaurant             Restaurant  
2    Light Rail Station            Comic Shop            Pizza Place  
3                   Bar          Airport Gate     Airport Food Court  
4       Thai Restaurant          Burger Joint            Salad Place

In [31]:
neighborhoods_venues_cluster.insert(0, 'Cluster Labels', kmeans.labels_)

In [32]:
toronto_merged = df_poscoord

# merge toronto_grouped with toronto_data to add latitude/longitude for each neighborhood
toronto_merged = toronto_merged.join(neighborhoods_venues_cluster.set_index('Neighborhood'), on = 'Neighborhood')

toronto_merged.head() # check the last columns!

PostalCode           Borough                                 Neighborhood  \
0        M5A  Downtown Toronto                    Regent Park, Harbourfront   
1        M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government   
2        M5B  Downtown Toronto                     Garden District, Ryerson   
3        M5C  Downtown Toronto                               St. James Town   
4        M4E      East Toronto                                  The Beaches   

    Latitude  Longitude  Cluster Labels 1st Most Common Venue  \
0  43.654260 -79.360636               7           Coffee Shop   
1  43.662301 -79.389494               7           Coffee Shop   
2  43.657162 -79.378937               7        Clothing Store   
3  43.651494 -79.375418               7           Coffee Shop   
4  43.676357 -79.293031               5     Health Food Store   

  2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
0                Bakery                   Pub                  Park   
1           Yoga Studio      Sushi Restaurant   Distribution Center   
2           Coffee Shop                  Café   Japanese Restaurant   
3                  Café          Cocktail Bar   American Restaurant   
4                   Pub                 Trail         Women's Store   

  5th Most Common Venue 6th Most Common Venue 7th Most Common Venue  \
0               Theater        Breakfast Spot                  Café   
1         Burrito Place   Japanese Restaurant    Italian Restaurant   
2        Cosmetics Shop       Bubble Tea Shop            Restaurant   
3             Gastropub               Theater            Restaurant   
4         Deli / Bodega      Department Store          Dessert Shop   

       8th Most Common Venue 9th Most Common Venue 10th Most Common Venue  
0                 Shoe Store     Electronics Store            Event Space  
1                      Diner           Music Venue          Smoothie Shop  
2  Middle Eastern Restaurant    Italian Restaurant                  Hotel  
3           Department Store    Italian Restaurant         Clothing Store  
4         Dim Sum Restaurant                 Diner         Discount Store

In [54]:
# create map
map_clusters = folium.Map(location = [latitude, longitude], zoom_start = 12)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(toronto_merged['Latitude'], toronto_merged['Longitude'], toronto_merged['Neighborhood'], toronto_merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius = 5,
        popup = label,
        color = rainbow[cluster-1],
        fill = True,
        fill_color = rainbow[cluster-1],
        fill_opacity = 0.7).add_to(map_clusters)
       
map_clusters

In [61]:
# as folium maps will not display on GitHub, save it as an html file then display
map_clusters.save('after_clustering.html')

In [62]:
%%HTML
<iframe width = "100%" height = "700" src = "after_clustering.html"></iframe>

**Examine clusters**

* __Cluster 1: Food and Coffee__

In [34]:
toronto_merged.loc[toronto_merged['Cluster Labels'] == 0, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

Borough  Cluster Labels 1st Most Common Venue  \
7   Downtown Toronto               0         Grocery Store   
9       West Toronto               0              Pharmacy   
11      West Toronto               0                   Bar   
12      East Toronto               0      Greek Restaurant   
14      West Toronto               0                  Café   
15      East Toronto               0  Fast Food Restaurant   
17      East Toronto               0                  Café   
22      West Toronto               0                Bakery   
23   Central Toronto               0        Clothing Store   
24   Central Toronto               0                  Café   
25      West Toronto               0             Gift Shop   
26   Central Toronto               0        Sandwich Place   
27  Downtown Toronto               0                  Café   
28      West Toronto               0           Pizza Place   
30  Downtown Toronto               0                  Café   
35  Downtown Toronto               0                  Café   
38      East Toronto               0           Yoga Studio   

   2nd Most Common Venue  3rd Most Common Venue   4th Most Common Venue  \
7                   Café                   Park      Athletics & Sports   
9                 Bakery                   Park                    Café   
11            Restaurant       Asian Restaurant             Men's Store   
12           Coffee Shop     Italian Restaurant  Furniture / Home Store   
14           Coffee Shop         Breakfast Spot               Nightclub   
15      Sushi Restaurant                    Pub          Sandwich Place   
17           Coffee Shop              Gastropub     American Restaurant   
22    Mexican Restaurant                   Café         Thai Restaurant   
23           Coffee Shop            Yoga Studio      Chinese Restaurant   
24        Sandwich Place            Coffee Shop                Pharmacy   
25        Breakfast Spot             Restaurant           Movie Theater   
26          Dessert Shop            Coffee Shop        Sushi Restaurant   
27                Bakery                    Bar               Bookstore   
28           Coffee Shop                   Café                     Pub   
30                Bakery  Vietnamese Restaurant      Mexican Restaurant   
35           Coffee Shop                 Bakery      Italian Restaurant   
38         Auto Workshop          Garden Center                  Garden   

            5th Most Common Venue 6th Most Common Venue  \
7                      Baby Store           Candy Store   
9       Middle Eastern Restaurant                  Bank   
11  Vegetarian / Vegan Restaurant                  Café   
12                     Restaurant        Ice Cream Shop   
14                         Bakery     Convenience Store   
15                   Liquor Store    Italian Restaurant   
17                        Brewery                Bakery   
22                           Park                   Bar   
23                   Dessert Shop    Salon / Barbershop   
24              Indian Restaurant           Flower Shop   
25    Eastern European Restaurant               Dog Run   
26                            Gym    Italian Restaurant   
27            Japanese Restaurant            Restaurant   
28               Sushi Restaurant    Italian Restaurant   
30                   Dessert Shop           Coffee Shop   
35                     Restaurant           Pizza Place   
38           Gym / Fitness Center  Fast Food Restaurant   

        7th Most Common Venue          8th Most Common Venue  \
7          Italian Restaurant                          Diner   
9                         Bar                           Pool   
11                   Boutique                        Brewery   
12             Cosmetics Shop                        Brewery   
14                        Bar                   Intersection   
15              Burrito Place                   Intersection   
17  Latin American Restaurant     

* __Cluster 2: Residential Center__

In [35]:
toronto_merged.loc[toronto_merged['Cluster Labels'] == 1, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

Borough  Cluster Labels 1st Most Common Venue  \
21  Central Toronto               1                  Park   

   2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
21         Jewelry Store                 Trail              Bus Line   

   5th Most Common Venue 6th Most Common Venue        7th Most Common Venue  \
21      Sushi Restaurant         Deli / Bodega  Eastern European Restaurant   

   8th Most Common Venue 9th Most Common Venue 10th Most Common Venue  
21            Donut Shop      Doner Restaurant                Dog Run

* __Cluster 3: Plaza with a Garden__

In [36]:
toronto_merged.loc[toronto_merged['Cluster Labels'] == 2, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

Borough  Cluster Labels 1st Most Common Venue  \
19  Central Toronto               2                Garden   

   2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
19          Home Service         Women's Store          Dance Studio   

   5th Most Common Venue        6th Most Common Venue 7th Most Common Venue  \
19     Electronics Store  Eastern European Restaurant            Donut Shop   

   8th Most Common Venue 9th Most Common Venue 10th Most Common Venue  
19      Doner Restaurant               Dog Run    Distribution Center

* __Cluster 4: Residential Center with a Playground__

In [37]:
toronto_merged.loc[toronto_merged['Cluster Labels'] == 3, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

Borough  Cluster Labels 1st Most Common Venue  \
33  Downtown Toronto               3                  Park   

   2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
33            Playground                 Trail          Cupcake Shop   

          5th Most Common Venue 6th Most Common Venue 7th Most Common Venue  \
33  Eastern European Restaurant            Donut Shop      Doner Restaurant   

   8th Most Common Venue 9th Most Common Venue 10th Most Common Venue  
33               Dog Run   Distribution Center         Discount Store

* __Cluster 5: Plaza with a Playground__

In [38]:
toronto_merged.loc[toronto_merged['Cluster Labels'] == 4, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

Borough  Cluster Labels 1st Most Common Venue  \
29  Central Toronto               4            Playground   

   2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
29           Summer Camp            Restaurant         Women's Store   

   5th Most Common Venue 6th Most Common Venue 7th Most Common Venue  \
29          Cupcake Shop            Donut Shop      Doner Restaurant   

   8th Most Common Venue 9th Most Common Venue 10th Most Common Venue  
29               Dog Run   Distribution Center         Discount Store

* __Cluster 6: Home Services__

In [39]:
toronto_merged.loc[toronto_merged['Cluster Labels'] == 5, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

Borough  Cluster Labels 1st Most Common Venue 2nd Most Common Venue  \
4  East Toronto               5     Health Food Store                   Pub   

  3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
4                 Trail         Women's Store         Deli / Bodega   

  6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  \
4      Department Store          Dessert Shop    Dim Sum Restaurant   

  9th Most Common Venue 10th Most Common Venue  
4                 Diner         Discount Store

* __Cluster 7: Still Home Services__

In [40]:
toronto_merged.loc[toronto_merged['Cluster Labels'] == 6, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

Borough  Cluster Labels 1st Most Common Venue  \
18  Central Toronto               6                  Park   

   2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
18    Dim Sum Restaurant              Bus Line           Swim School   

   5th Most Common Venue 6th Most Common Venue        7th Most Common Venue  \
18         Deli / Bodega     Electronics Store  Eastern European Restaurant   

   8th Most Common Venue 9th Most Common Venue 10th Most Common Venue  
18            Donut Shop      Doner Restaurant                Dog Run

* __Cluster 8: Coffee Shops__

In [41]:
toronto_merged.loc[toronto_merged['Cluster Labels'] == 7, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

Borough  Cluster Labels 1st Most Common Venue  \
0   Downtown Toronto               7           Coffee Shop   
1   Downtown Toronto               7           Coffee Shop   
2   Downtown Toronto               7        Clothing Store   
3   Downtown Toronto               7           Coffee Shop   
5   Downtown Toronto               7           Coffee Shop   
6   Downtown Toronto               7           Coffee Shop   
8   Downtown Toronto               7           Coffee Shop   
10  Downtown Toronto               7           Coffee Shop   
13  Downtown Toronto               7           Coffee Shop   
16  Downtown Toronto               7           Coffee Shop   
31   Central Toronto               7                   Pub   
34  Downtown Toronto               7           Coffee Shop   
36  Downtown Toronto               7           Coffee Shop   
37  Downtown Toronto               7           Coffee Shop   

   2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
0                 Bakery                   Pub                  Park   
1            Yoga Studio      Sushi Restaurant   Distribution Center   
2            Coffee Shop                  Café   Japanese Restaurant   
3                   Café          Cocktail Bar   American Restaurant   
5           Cocktail Bar    Seafood Restaurant              Beer Bar   
6     Italian Restaurant                  Café        Sandwich Place   
8                   Café            Restaurant         Deli / Bodega   
10              Aquarium                  Café                 Hotel   
13                  Café                 Hotel            Restaurant   
16                  Café            Restaurant                 Hotel   
31           Coffee Shop   American Restaurant            Bagel Shop   
34                  Café   Japanese Restaurant          Cocktail Bar   
36                  Café                   Gym   Japanese Restaurant   
37   Japanese Restaurant      Sushi Restaurant            Restaurant   

   5th Most Common Venue 6th Most Common Venue 7th Most Common Venue  \
0                Theater        Breakfast Spot                  Café   
1          Burrito Place   Japanese Restaurant    Italian Restaurant   
2         Cosmetics Shop       Bubble Tea Shop            Restaurant   
3              Gastropub               Theater            Restaurant   
5                 Bakery           Cheese Shop                  Café   
6                    Bar   Japanese Restaurant        Ice Cream Shop   
8         Clothing Store                   Gym       Thai Restaurant   
10            Restaurant    Italian Restaurant   Fried Chicken Joint   
13   Japanese Restaurant   American Restaurant    Seafood Restaurant   
16   American Restaurant                   Gym    Seafood Restaurant   
31           Supermarket                  Bank            Sports Bar   
34            Restaurant    Italian Restaurant              Beer Bar   
36            Restaurant                 Hotel    Seafood Restaurant   
37               Gay Bar           Yoga Studio             Gastropub   

        8th Most Common Venue 9th Most Common Venue 10th Most Common Venue  
0                  Shoe Store     Electronics Store            Event Space  
1                       Diner           Music Venue          Smoothie Shop  
2   Middle Eastern Restaurant    Italian Restaurant                  Hotel  
3            Department Store    Italian Restaurant         Clothing Store  
5                  Restaurant                   Pub          Shopping Mall  
6             Thai Restaurant          Burger Joint            Salad Place  
8                       Hotel            Steakhouse            Salad Place  
10        Sporting Goods Shop               Brewery         Scenic Lookout  
13         Italian Restaurant           Salad Place    Sporting Goods Shop  
16              Deli / Bodega    Italian Restaurant    Japanese Restaurant  
31                 Restaurant           Pizza Place    Fried Chicken Join

* __Cluster 9: Plaza with a Park__

In [42]:
toronto_merged.loc[toronto_merged['Cluster Labels'] == 8, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

Borough  Cluster Labels 1st Most Common Venue  \
20  Central Toronto               8                  Park   

   2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
20      Department Store        Breakfast Spot        Sandwich Place   

   5th Most Common Venue 6th Most Common Venue 7th Most Common Venue  \
20     Food & Drink Shop                 Hotel                   Gym   

   8th Most Common Venue 9th Most Common Venue 10th Most Common Venue  
20            Comic Shop            Donut Shop       Doner Restaurant

* __Cluster 10: Airport Region__

In [43]:
toronto_merged.loc[toronto_merged['Cluster Labels'] == 9, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

Borough  Cluster Labels 1st Most Common Venue  \
32  Downtown Toronto               9       Airport Service   

   2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
32      Airport Terminal        Airport Lounge         Boat or Ferry   

   5th Most Common Venue 6th Most Common Venue 7th Most Common Venue  \
32           Coffee Shop       Harbor / Marina      Sculpture Garden   

   8th Most Common Venue 9th Most Common Venue 10th Most Common Venue  
32                   Bar          Airport Gate     Airport Food Court

<h2><a href = "#0" style = "text-decoration:none;">Back to Top ↑</a></h2>